name: Проверка на pre-commit коммитов

on: 
  push:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - '!master'   # excludes master
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Test commit
        run: pre-commit run -a 